name: JobActions
version: '${project.version}'
main: dk.arasbuilds.jobactions.JobActions
api-version: '1.21'
softdepend: [Vault]

commands:
  order:
    description: "General Order"
    usage: "/order [create/list/market/remove] [ID/Player/Nr]"
  market:
    description: "Opens Market"
    usage: "/market"